version: "3"
services:
    fbird-be:
        image: vote-app
        restart: unless-stopped
        build: .
        ports:
            - "8088:8001"
        depends_on:
            - mongo
        environment:
            - DB_HOST=mongo
            - DB_NAME=${DB_NAME}
            - DB_PORT=27017
            - PORT=8001

    mongo:
        image: mongo:latest
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: 
            MONGO_INITDB_ROOT_PASSWORD: 
            MONGO_INITDB_DATABASE: ${DB_NAME}
        ports:
            - ${DB_PORT}:27017
        volumes:
            - ./data/mongo:/data/db


# PORT=8002
# DB_HOST=db
# DB_PORT=30004
# DB_NAME=fbird_database